//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string adres { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> post { get; set; }
        public Nullable<int> gender { get; set; }
    
        public virtual Gender Gender1 { get; set; }
        public virtual Post Post1 { get; set; }
    }
}
