//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piza
{
    using System;
    using System.Collections.Generic;
    
    public partial class main
    {
        public int id { get; set; }
        public Nullable<int> product { get; set; }
        public Nullable<int> client { get; set; }
        public Nullable<int> metodDost { get; set; }
        public string adres { get; set; }
        public Nullable<int> metodOforml { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual MetodDost MetodDost1 { get; set; }
        public virtual MetOforml MetOforml { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
